export interface StackInfo {
  language: string;
  runtime: string;
  build: string;
  framework: string;
  extras: string[];
}

export const executorMd = (
  projectName: string,
  description: string,
  executorName = "Claude Code",
  architectFile = "GEMINI.md",
) =>
  `# ${projectName} — Executor Instructions

<!-- LLM_CONTEXT: Executor instructions for ${executorName} -->
<!-- Generated by Tocket CLI -->

## Role

You are the **Executor** (${executorName}) for **${projectName}**.
${description ? `\n> ${description}\n` : ""}
Your job is to **implement**, not to plan. Read the Memory Bank before every session, follow the Architect's decisions, and write code.

---

## Rules

1. **Always read \`.context/\` first** — Start every session by reading activeContext.md and systemPatterns.md.
2. **Follow the Architect's plan** — Implementation decisions come from \`${architectFile}\` or mission briefs. Do not redesign.
3. **Ask before deviating** — If the plan is unclear or blocked, ask the user. Do not improvise architecture.
4. **Write code in English** — Variables, functions, comments, commits — all in \`en-US\`.
5. **Update Memory Bank on completion** — After finishing a task, update activeContext.md with what changed.
6. **Before expensive tools** — Read \`AGENTS.md\` and \`.context/decisions/\` first. If a handoff exists, honor it (do not re-ask Jev). Else run \`tocket decide\`. Workers execute. Tocket does not.
7. **Tool-risk gate** — Before bash, deploy, or browser: \`tocket decide --choice tool_gate:allow,block,ask\`, then \`tocket work\`. Honor \`allow|block|ask\`. Consume with \`tocket work\` (plan) or \`tocket work --apply\` (receipt).

---

## Memory Bank

| File | Purpose |
|------|---------|
| \`.context/activeContext.md\` | Current focus, recent changes, open decisions |
| \`.context/systemPatterns.md\` | Architecture patterns, tech stack, conventions |
| \`${architectFile}\` | Architect instructions (read-only for you) |

---

## Workflow

\`\`\`
1. Read .context/  →  2. Receive task  →  3. Implement  →  4. Update .context/
\`\`\`
`;

/** @deprecated Use executorMd instead */
export const claudeMd = executorMd;

export const architectMd = (
  projectName: string,
  description: string,
  architectName = "Gemini",
  executorName = "Claude Code",
  executorFile = "CLAUDE.md",
) =>
  `# ${projectName} — Architect Instructions

<!-- LLM_CONTEXT: Architect instructions for ${architectName} -->
<!-- Generated by Tocket CLI -->

## Role

You are the **Architect** (${architectName}) for **${projectName}**.
${description ? `\n> ${description}\n` : ""}
Your job is to **analyze, plan, and decide**. You do not write code directly — you produce structured mission briefs that the Executor (${executorName}) implements.

---

## Rules

1. **Read \`.context/\` first** — Understand current state before planning.
2. **Produce payloads** — Use \`<payload version="2.0">\` XML format for handoff to the Executor.
3. **Never write code inline** — Provide specs, not implementations. The Executor handles code.
4. **Update systemPatterns.md** — When you make architectural decisions, record them.
5. **Think in constraints** — Define what the system should and should not do.
6. **Jev is the judge, not the writer** — Cheap next-move Choice goes to \`tocket decide\`. Do not ask Jev to write prose or run tools.

---

## Memory Bank

| File | Purpose |
|------|---------|
| \`.context/activeContext.md\` | Current focus, recent changes, open decisions |
| \`.context/systemPatterns.md\` | Architecture patterns, tech stack, conventions |
| \`${executorFile}\` | Executor instructions (read-only for you) |

---

## Payload Format

\`\`\`xml
<payload version="2.0">
  <meta>
    <intent>What needs to happen</intent>
    <scope>Which files/modules are affected</scope>
    <priority>high | medium | low</priority>
  </meta>
  <context>
    <summary>Background and reasoning</summary>
    <architect-decisions>Key decisions made</architect-decisions>
  </context>
  <tasks>
    <task id="1" type="create|edit|delete">
      <target>file/path</target>
      <action>What to do</action>
      <spec>Detailed specification</spec>
      <done>Definition of done</done>
    </task>
  </tasks>
  <validate>
    <check>Verification step</check>
  </validate>
</payload>
\`\`\`
`;

/** @deprecated Use architectMd instead */
export const geminiMd = architectMd;

export const activeContextMd = (projectName: string) =>
  `# Active Context - ${projectName}

<!-- Updated by both Architect and Executor after each session -->

## Current Focus

_No active tasks yet. Run \`tocket generate\` to create your first mission brief._

## Recent Changes

| Date | Change | Agent |
|------|--------|-------|
| ${new Date().toISOString().split("T")[0]} | Initialized agentic workspace | Tocket CLI |

## Open Decisions

_None yet._
`;

export const systemPatternsMd = (
  projectName: string,
  architectName = "Gemini",
  executorName = "Claude Code",
) =>
  `# System Patterns - ${projectName}

<!-- Architectural decisions and conventions. Updated by the Architect. -->

## Tech Stack

_To be defined by the Architect._

## Architecture Patterns

_To be defined._

## Conventions

- Code language: \`en-US\`
- Commit language: \`en-US\`
- Triangulation: ${architectName} (Architect) + ${executorName} (Executor)

## Key Decisions

| Decision | Rationale | Date |
|----------|-----------|------|
| Adopted Tocket triangulation | Structured multi-agent workflow | ${new Date().toISOString().split("T")[0]} |
`;

export const productContextMd = (projectName: string, description: string) =>
  `# Product Context - ${projectName}

<!-- What the product is, who it's for, and why it exists. Updated by the Architect. -->

## What is ${projectName}?

${description || "_Describe your product here._"}

## Problem

_What problem does this project solve?_

## Solution

_How does it solve it?_

## Target Users

_Who is this for?_

## Design Principles

- _List the guiding principles for this project_
`;

export const techContextMd = (projectName: string, stack?: StackInfo) => {
  const lang = stack?.language || "";
  const rt = stack?.runtime || "";
  const bld = stack?.build || "";
  const fw = stack?.framework || "";
  const extras = stack?.extras?.length
    ? `\n### Notable Dependencies\n\n${stack.extras.map((d) => `- \`${d}\``).join("\n")}\n`
    : "";

  return `# Tech Context - ${projectName}

<!-- Stack, build tools, and critical rules. Updated by the Architect. -->

## Stack

| Layer | Technology | Notes |
|-------|-----------|-------|
| Language | ${lang} | ${lang ? "Auto-detected by Tocket" : ""} |
| Runtime | ${rt} | ${rt ? "Auto-detected by Tocket" : ""} |
| Build | ${bld} | ${bld ? "Auto-detected by Tocket" : ""} |
| Framework | ${fw} | ${fw ? "Auto-detected by Tocket" : ""} |
${extras}
## Critical Rules

_Document any rules that agents must follow (e.g., import conventions, naming patterns)._

## Project Structure

\`\`\`
${projectName}/
  src/         # Source code
  .context/    # Memory Bank
\`\`\`
`;
};

export const progressMd = (projectName: string) =>
  `# Progress Log - ${projectName}

<!-- Appended by tocket sync and manual updates -->

## Milestone: Project Initialization

**Status**: Complete

- [x] Agentic workspace scaffolded with Tocket CLI
- [x] Memory Bank initialized (\`.context/\`)

## Next Up

- [ ] _Define your first milestone here_
`;

export const cursorrulesMd = (
  projectName: string,
  description: string,
  architectFile = "ARCHITECT.md",
) =>
  `# .cursorrules - ${projectName}

# Generated by Tocket CLI — compatible with Cursor IDE

## Role

You are the **Executor** (Cursor) for **${projectName}**.
${description ? `\n> ${description}\n` : ""}
Your job is to **implement**, not to plan. Read the Memory Bank before every session, follow the Architect's decisions, and write code.

## Rules

1. **Always read \`.context/\` first** — Start every session by reading activeContext.md and systemPatterns.md.
2. **Follow the Architect's plan** — Implementation decisions come from \`${architectFile}\` or mission briefs. Do not redesign.
3. **Ask before deviating** — If the plan is unclear or blocked, ask the user. Do not improvise architecture.
4. **Write code in English** — Variables, functions, comments, commits — all in \`en-US\`.
5. **Update Memory Bank on completion** — After finishing a task, update activeContext.md with what changed.
6. **Before expensive tools** — Read \`AGENTS.md\` and \`.context/decisions/\` first. If a handoff exists, honor it (do not re-ask Jev). Else run \`tocket decide\`.
7. **Tool-risk gate** — Before bash, deploy, or browser: \`tocket decide --choice tool_gate:allow,block,ask\`, then \`tocket work\`. Honor \`allow|block|ask\`.

## Memory Bank

| File | Purpose |
|------|---------|
| \`.context/activeContext.md\` | Current focus, recent changes, open decisions |
| \`.context/systemPatterns.md\` | Architecture patterns, tech stack, conventions |
| \`${architectFile}\` | Architect instructions (read-only for you) |

## Workflow

\`\`\`
1. Read .context/  →  2. Receive task  →  3. Implement  →  4. Update .context/
\`\`\`
`;

export const tocketMd = (
  projectName: string,
  executorFile = "CLAUDE.md",
  architectFile = "GEMINI.md",
) =>
  `# Tocket Protocol Specification

> How any AI agent should operate in **${projectName}**.

This file is **agent-agnostic**. Whether you are Claude, Gemini, GPT, Cursor, Cline, Copilot, or any future AI — if you see this file, follow these rules.

---

## 1. Memory Bank

Project context lives in \`.context/\`, not in chat history. **Read it before doing anything.**

\`\`\`
.context/
  activeContext.md    <- Start here. Current focus, recent changes, open decisions.
  systemPatterns.md   <- Architecture patterns, conventions, key decisions.
  techContext.md      <- Tech stack, build tools, critical rules.
  productContext.md   <- What the product is, who it's for, why it exists.
  progress.md         <- What's done, what's next.
  gotchas/            <- Optional section packs (frontend.md, path-src-api.md).
  active/packs.md     <- Packs loaded for the current query.
  attention/          <- Meta-attention receipts. Jev judges chunks.
  handoffs/           <- Filtered handoff markdown.
\`\`\`

### Rules

- **Read before acting** — Always read \`activeContext.md\` and \`systemPatterns.md\` before your first action in a session.
- **Write before leaving** — Update \`activeContext.md\` with what changed after completing significant work.
- **Trust the files** — If \`.context/\` says the project uses ESM, it uses ESM. Don't second-guess documented decisions.
- **Don't duplicate** — Context belongs in \`.context/\`, not scattered in code comments or chat summaries.
- **Decide is a file** — \`tocket decide\` writes the next move into \`.context/decisions/\`. Before expensive tools, run it or read the latest decision. Consume it with \`tocket work\` (plan) or \`tocket work --apply\` (notebook receipt). Workers (Cursor, Claude, GrokBot, CI) execute. Tocket does not re-decide.
- **Do not re-ask Jev** — If a decision file already exists, honor \`choice\`, \`destination\`, \`gated\`, and \`tool_gate\`. Call \`tocket work\`, not \`tocket decide\` again.
- **Tool-risk gate** — \`tool_gate\` / \`action_gate\` is \`allow|block|ask\`. \`tocket work --apply\` refuses \`block\` and \`ask\` unless \`--force\`. Shadow / log-only still needs \`--force\`.

---

## 2. Triangulation

Tocket separates **planning** from **implementation** across two agent roles:

\`\`\`
┌─────────────────┐          ┌─────────────────┐
│    ARCHITECT     │          │    EXECUTOR      │
│  (Planner)       │  payload │  (Implementer)   │
│                  │─────────>│                  │
│  Analyzes task   │          │  Receives plan   │
│  Designs approach│          │  Writes code     │
│  Generates XML   │          │  Runs tests      │
│  Updates patterns│          │  Updates context  │
└─────────────────┘          └─────────────────┘
\`\`\`

### Architect

- Reads \`.context/\` to understand current state
- Produces structured payloads (see Section 3) with clear tasks
- Makes architectural decisions and records them in \`systemPatterns.md\`
- **Does not write code** — only specs and constraints

### Executor

- Reads \`.context/\` and the Architect's payload
- Implements tasks exactly as specified
- Asks when the plan is unclear — does not improvise architecture
- Updates \`activeContext.md\` and \`progress.md\` after completing work

### Solo Mode

Not every task needs triangulation. For simple, well-defined changes, a single agent can act as both Architect and Executor. The Memory Bank rules still apply.

---

## 3. Payloads

A payload is the structured handoff from Architect to Executor.

### Minimal Example

\`\`\`xml
<payload version="2.0">
  <meta>
    <intent>Goal in one line</intent>
    <scope>Files affected</scope>
    <priority>high | medium | low</priority>
  </meta>
  <tasks>
    <task id="1" type="create | edit | delete">
      <target>file/path</target>
      <action>What to do</action>
      <done>Definition of done</done>
    </task>
  </tasks>
  <validate>
    <check>How to verify success</check>
  </validate>
</payload>
\`\`\`

---

## 4. Decide and work

Jev (or the stub) is the **judge**, not the writer. \`tocket decide\` writes JSON. \`tocket work\` plans (default) then \`--apply\` stamps a notebook receipt. Tocket does not run tools.

| Step | Command | Rule |
| --- | --- | --- |
| Judge | \`tocket decide\` | Writes \`.context/decisions/\`. Shadow-first: \`--dry-run\` / \`--shadow\` is log-only. Optional \`TYPESAFE_API_KEY\` (stub without it). |
| Gate | \`--choice tool_gate:allow,block,ask\` | Before bash, deploy, or browser. |
| Plan | \`tocket work --from <decision>\` | Dry-run. Never calls Jev. |
| Apply | \`tocket work --apply\` | Receipt only if gate is \`allow\` or missing. \`block\`/\`ask\` exit 2 unless \`--force\`. |
| Fork | \`--fork agent\\|model\\|tool\\|action\\|human\` | Bounded. \`--fork model\` is the cheap model-router hook. \`human\` always reviews. |

---

## Quick Start

1. Read \`AGENTS.md\` (single source agents read first), then this file (\`TOCKET.md\`)
2. Read \`.context/activeContext.md\` for current state
3. Read your role-specific config (\`${executorFile}\` or \`${architectFile}\`)
4. If \`.context/decisions/\` already has a handoff, honor it. Do not re-ask Jev.
5. Proceed with your task, following the Memory Bank rules above
`;

/** Shared decide/work/gate rules for AGENTS.md (init template and `tocket agents-md`). */
export function agentsProtocolSection(): string {
  return `## How Tocket works

Tocket is the shared notebook (\`.context/\`). Agents work. Tocket remembers. Jev only chooses the next step.

1. Read this file, then \`.context/activeContext.md\` and \`.context/systemPatterns.md\`, before expensive tools.
2. If \`.context/decisions/\` already has a handoff, honor \`choice\`, \`destination\`, \`gated\`, and \`tool_gate\`. Do not call \`tocket decide\` again (do not re-ask Jev).
3. \`tocket decide\` is the judge (Jev or stub). \`tocket work\` is the plan (dry-run). \`tocket work --apply\` stamps a notebook receipt. Never re-decide.
4. Honor \`tool_gate\`: \`allow\` proceeds, \`block\` stops, \`ask\` escalates to a human. Shadow / log-only is advice unless \`--force\`.
5. Before bash, deploy, or browser: \`tocket decide --choice tool_gate:allow,block,ask\`, then \`tocket work\`.
6. Meta-attention handoff: \`tocket handoff --aware\` asks Jev (or the stub) to score \`.context/\` chunks. Workers read the filtered handoff, not the whole Memory Bank.
7. Conditional packs live in \`.context/gotchas/\`. \`tocket packs load --query\` writes the relevant packs to \`.context/active/packs.md\`.

Optional \`TYPESAFE_API_KEY\` for live Jev. Without it, decide uses the stub. Prefer \`--dry-run\` or \`--shadow\` first.
`;
}

export const agentsMd = (
  projectName: string,
  description: string,
  executorName = "Claude Code",
  architectName = "Gemini",
) =>
  `# AGENTS.md — ${projectName}

> Written by \`tocket init\`. Refresh project facts with \`tocket agents-md\`. Keep the decide/work rules below.

## About this project

${description || "_No description provided._"}

## Instructions for AI agents

1. Read this file first, then \`.context/activeContext.md\`
2. Read \`.context/systemPatterns.md\` for architecture decisions and conventions
3. Update \`.context/activeContext.md\` after completing significant work
4. Follow the full protocol in \`TOCKET.md\`

${agentsProtocolSection()}
## Current Focus

_Generated from .context/activeContext.md. Run \`tocket agents-md\` to update._

## Tech Stack

_Generated from .context/techContext.md. Run \`tocket agents-md\` to update._

## Architecture & Conventions

_Generated from .context/systemPatterns.md. Run \`tocket agents-md\` to update._

## Key Rules

- Write all code, comments, and commits in \`en-US\`
- Do not improvise architecture. Follow documented decisions
- Context belongs in \`.context/\`, not in code comments or chat
- Triangulation: ${architectName} (Architect) + ${executorName} (Executor)
`;

/** Official portable skill for Cursor / Claude / Codex. Written by `tocket init`. */
export const TOCKET_SKILL_REL = ".agents/skills/tocket/SKILL.md";
/** Catalog path so `npx skills add pedrocivita/tocket --skill tocket` can discover it. */
export const TOCKET_SKILL_CATALOG_REL = "skills/tocket/SKILL.md";
export const TOCKET_SKILLS_ADD = "npx skills add pedrocivita/tocket --skill tocket";
export const TOCKET_AGENT_PHRASE =
  "Before expensive tools: tocket decide --dry-run, or read .context/decisions/.";

export function tocketConventionsHint(): string {
  return [
    "On disk (agents already read these):",
    "  AGENTS.md                      start here (any agent)",
    "  .context/                      shared notebook",
    "  .context/decisions/            next move (tocket decide)",
    "  .context/attention/            meta-attention receipts",
    "  .context/gotchas/              conditional packs",
    `  ${TOCKET_SKILL_REL}  official skill`,
    `One-shot: ${TOCKET_SKILLS_ADD}`,
    `Phrase: ${TOCKET_AGENT_PHRASE}`,
  ].join("\n");
}

export const tocketSkillMd = () => `---
name: tocket
description: Shared .context/ notebook. Before expensive tools, run tocket decide --dry-run or read .context/decisions/. Workers execute; Tocket does not.
---

# Tocket

Tocket is the shared project notebook (\`.context/\`). Agents read and write those files. \`tocket decide\` writes the next move as JSON. Workers (Cursor, Claude, GrokBot, CI) execute. Tocket does not.

**${TOCKET_AGENT_PHRASE}**

Harness your context. Jev is the judge, not the writer. Meta-attention handoff: Jev judges chunks; workers read the filtered handoff.

## When to use

- Read \`AGENTS.md\` and \`.context/\` before expensive tools.
- If \`.context/decisions/\` already has a handoff, honor it. Do not re-ask Jev.
- \`tocket decide\` = judge (Jev or stub). \`tocket work\` = plan. \`tocket work --apply\` = receipt.
- Honor \`tool_gate\` (\`allow|block|ask\`). Before bash/deploy/browser: \`--choice tool_gate:allow,block,ask\`, then \`tocket work\`.
- \`tocket handoff --aware --query "..."\` filters \`.context/\` chunks. Receipt: \`.context/attention/\`. Filtered handoff: \`.context/handoffs/\`.
- Gotcha packs live in \`.context/gotchas/\`. \`tocket packs load --query "..."\` writes \`.context/active/packs.md\`.
- After work: update \`.context/activeContext.md\`.

## Setup

\`\`\`bash
npx @pedrocivita/tocket init
${TOCKET_SKILLS_ADD}
tocket doctor
tocket decide --dry-run --state '{"goal":"docs"}' --choice next:research,write,review
\`\`\`

- Optional \`TYPESAFE_API_KEY\` for live Jev. Never paste API keys into chat.
- Prefer \`--dry-run\` or \`--shadow\` first.
- Run \`tocket doctor\` for green/yellow/red setup checks.

## Do not

- Do not ask Tocket to write prose, do math, or run workers.
- Do not rebuild the app around Jev. Swap this decision node in.
`;
