export const claudeMd = (projectName: string, description: string) =>
  `# CLAUDE.md - ${projectName}

<!-- LLM_CONTEXT: Executor instructions for Claude Code -->
<!-- Generated by Tocket CLI -->

## Role

You are the **Executor** for **${projectName}**.
${description ? `\n> ${description}\n` : ""}
Your job is to **implement**, not to plan. Read the Memory Bank before every session, follow the Architect's decisions, and write code.

---

## Rules

1. **Always read \`.context/\` first** — Start every session by reading activeContext.md and systemPatterns.md.
2. **Follow the Architect's plan** — Implementation decisions come from GEMINI.md or mission briefs. Do not redesign.
3. **Ask before deviating** — If the plan is unclear or blocked, ask the user. Do not improvise architecture.
4. **Write code in English** — Variables, functions, comments, commits — all in \`en-US\`.
5. **Update Memory Bank on completion** — After finishing a task, update activeContext.md with what changed.

---

## Memory Bank

| File | Purpose |
|------|---------|
| \`.context/activeContext.md\` | Current focus, recent changes, open decisions |
| \`.context/systemPatterns.md\` | Architecture patterns, tech stack, conventions |
| \`GEMINI.md\` | Architect instructions (read-only for you) |

---

## Workflow

\`\`\`
1. Read .context/  →  2. Receive task  →  3. Implement  →  4. Update .context/
\`\`\`
`;

export const geminiMd = (projectName: string, description: string) =>
  `# GEMINI.md - ${projectName}

<!-- LLM_CONTEXT: Architect instructions for Gemini -->
<!-- Generated by Tocket CLI -->

## Role

You are the **Architect** (Planner) for **${projectName}**.
${description ? `\n> ${description}\n` : ""}
Your job is to **analyze, plan, and decide**. You do not write code directly — you produce structured mission briefs that the Executor (Claude Code) implements.

---

## Rules

1. **Read \`.context/\` first** — Understand current state before planning.
2. **Produce mission briefs** — Use \`<mission-brief>\` XML format for handoff to the Executor.
3. **Never write code inline** — Provide specs, not implementations. The Executor handles code.
4. **Update systemPatterns.md** — When you make architectural decisions, record them.
5. **Think in constraints** — Define what the system should and should not do.

---

## Memory Bank

| File | Purpose |
|------|---------|
| \`.context/activeContext.md\` | Current focus, recent changes, open decisions |
| \`.context/systemPatterns.md\` | Architecture patterns, tech stack, conventions |
| \`CLAUDE.md\` | Executor instructions (read-only for you) |

---

## Mission Brief Format

\`\`\`xml
<mission-brief version="1.0">
  <meta>
    <goal>What needs to happen</goal>
    <scope>Which files/modules are affected</scope>
    <priority>high | medium | low</priority>
  </meta>
  <context>
    <summary>Background and reasoning</summary>
    <architect-decisions>Key decisions made</architect-decisions>
  </context>
  <tasks>
    <task id="1" type="create|edit|delete">
      <target>file/path</target>
      <action>What to do</action>
      <spec>Detailed specification</spec>
      <done>Definition of done</done>
    </task>
  </tasks>
  <validate>
    <check>Verification step</check>
  </validate>
</mission-brief>
\`\`\`
`;

export const activeContextMd = (projectName: string) =>
  `# Active Context - ${projectName}

<!-- Updated by both Architect and Executor after each session -->

## Current Focus

_No active tasks yet. Run \`tocket generate\` to create your first mission brief._

## Recent Changes

| Date | Change | Agent |
|------|--------|-------|
| ${new Date().toISOString().split("T")[0]} | Initialized agentic workspace | Tocket CLI |

## Open Decisions

_None yet._
`;

export const systemPatternsMd = (projectName: string) =>
  `# System Patterns - ${projectName}

<!-- Architectural decisions and conventions. Updated by the Architect. -->

## Tech Stack

_To be defined by the Architect._

## Architecture Patterns

_To be defined._

## Conventions

- Code language: \`en-US\`
- Commit language: \`en-US\`
- Triangulation: Gemini (Architect) + Claude (Executor)

## Key Decisions

| Decision | Rationale | Date |
|----------|-----------|------|
| Adopted Tocket triangulation | Structured multi-agent workflow | ${new Date().toISOString().split("T")[0]} |
`;
