name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's missing or frustrating?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
  - type: dropdown
    id: contribute
    attributes:
      label: Would you be willing to contribute this?
      options:
        - "Yes, I'd like to submit a PR"
        - "Maybe, with some guidance"
        - "No, just suggesting"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other details, mockups, or examples.
