import type { Command } from "commander";
import { existsSync, readFileSync, watch } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { success, error as themeError, heading, info, dim } from "../utils/theme.js";
import { agentsMd } from "../templates/memory-bank.js";

interface ContextFiles {
  activeContext: string;
  systemPatterns: string;
  techContext: string;
  productContext: string;
}

function readContextFiles(cwd: string): ContextFiles {
  const contextDir = join(cwd, ".context");
  const activeContext = existsSync(join(contextDir, "activeContext.md"))
    ? readFileSync(join(contextDir, "activeContext.md"), "utf-8")
    : "";
  const systemPatterns = existsSync(join(contextDir, "systemPatterns.md"))
    ? readFileSync(join(contextDir, "systemPatterns.md"), "utf-8")
    : "";
  const techContext = existsSync(join(contextDir, "techContext.md"))
    ? readFileSync(join(contextDir, "techContext.md"), "utf-8")
    : "";
  const productContext = existsSync(join(contextDir, "productContext.md"))
    ? readFileSync(join(contextDir, "productContext.md"), "utf-8")
    : "";

  return { activeContext, systemPatterns, techContext, productContext };
}

function extractSection(content: string, sectionName: string): string {
  const lines = content.split("\n");
  const startIndex = lines.findIndex(line => line.includes(`## ${sectionName}`));

  if (startIndex === -1) return "";

  let endIndex = lines.length;
  for (let i = startIndex + 1; i < lines.length; i++) {
    if (lines[i].startsWith("## ")) {
      endIndex = i;
      break;
    }
  }

  return lines.slice(startIndex + 1, endIndex).join("\n").trim();
}

function generateAgentsMdContent(
  projectName: string,
  description: string,
  contextFiles: ContextFiles,
  executorName = "Claude Code",
  architectName = "Gemini",
): string {
  const currentFocus = extractSection(contextFiles.activeContext, "Current Focus");
  const techStack = extractSection(contextFiles.techContext, "Stack");
  const conventions = extractSection(contextFiles.systemPatterns, "Conventions");
  const keyDecisions = extractSection(contextFiles.systemPatterns, "Key Decisions");

  const architectureSection = extractSection(contextFiles.systemPatterns, "Architecture Patterns");

  const content = `# AGENTS.md — ${projectName}

> Auto-generated by [Tocket](https://tocket.ai) from \`.context/\`. Do not edit manually — run \`tocket agents-md\` to regenerate.

## About this project

${description || "_No description provided._"}

## Instructions for AI agents

1. Read \`.context/activeContext.md\` for current focus and recent changes
2. Read \`.context/systemPatterns.md\` for architecture decisions and conventions
3. Update \`.context/activeContext.md\` after completing significant work
4. Follow the full protocol in \`TOCKET.md\`

## Current Focus

${currentFocus || "_Generated from .context/activeContext.md. Run \`tocket agents-md\` to update._"}

## Tech Stack

${techStack || "_Generated from .context/techContext.md. Run \`tocket agents-md\` to update._"}

## Architecture & Conventions

${architectureSection ? `### Architecture Patterns\n\n${architectureSection}\n` : ""}
${conventions ? `### Conventions\n\n${conventions}\n` : ""}
${keyDecisions ? `### Key Decisions\n\n${keyDecisions}` : ""}

## Key Rules

- Write all code, comments, and commits in \`en-US\`
- Do not improvise architecture — follow documented decisions
- Context belongs in \`.context/\`, not in code comments or chat
- Triangulation: ${architectName} (Architect) + ${executorName} (Executor)
`;

  return content;
}

async function generateAndWrite(cwd: string, agentsMdPath: string, verbose: boolean = true): Promise<void> {
  const contextDir = join(cwd, ".context");
  const contextFiles = readContextFiles(cwd);

  let projectName = "Project";
  let description = "";

  const productContextFile = join(contextDir, "productContext.md");
  if (existsSync(productContextFile)) {
    const productContent = readFileSync(productContextFile, "utf-8");
    const nameMatch = productContent.match(/## What is (.+)\?/);
    if (nameMatch) projectName = nameMatch[1];

    const descMatch = productContent.match(/## What is .+\?\n\n(.+?)(?:\n\n##|$)/s);
    if (descMatch) description = descMatch[1].trim();
  }

  const activeContextFile = join(contextDir, "activeContext.md");
  if (existsSync(activeContextFile)) {
    const activeContent = readFileSync(activeContextFile, "utf-8");
    const nameMatch = activeContent.match(/# Active Context - (.+)/);
    if (nameMatch) projectName = nameMatch[1];
  }

  const systemPatternsFile = join(contextDir, "systemPatterns.md");
  let executorName = "Claude Code";
  let architectName = "Gemini";
  if (existsSync(systemPatternsFile)) {
    const systemContent = readFileSync(systemPatternsFile, "utf-8");
    const triangMatch = systemContent.match(/- Triangulation: (.+?) \(Architect\) \+ (.+?) \(Executor\)/);
    if (triangMatch) {
      architectName = triangMatch[1];
      executorName = triangMatch[2];
    }
  }

  const generatedContent = generateAgentsMdContent(
    projectName,
    description,
    contextFiles,
    executorName,
    architectName,
  );

  await writeFile(agentsMdPath, generatedContent, "utf-8");

  if (verbose) {
    console.log(heading("\n  AGENTS.md generated\n"));
    console.log(info(`Location: ${agentsMdPath}`));
    console.log(info(`Size: ${generatedContent.length} bytes`));
    console.log(success(`AGENTS.md is ready for cross-tool compatibility!\n`));
  }
}

export function registerAgentsMdCommand(program: Command): void {
  program
    .command("agents-md")
    .description("Generate or regenerate AGENTS.md from .context/")
    .option("--watch", "Watch for changes in .context/ and regenerate")
    .action(async (options: { watch?: boolean }) => {
      const cwd = process.cwd();
      const contextDir = join(cwd, ".context");
      const agentsMdPath = join(cwd, "AGENTS.md");

      if (!existsSync(contextDir)) {
        console.error(themeError("Memory Bank not found. Run 'tocket init' first."));
        process.exitCode = 1;
        return;
      }

      try {
        // Initial generation
        await generateAndWrite(cwd, agentsMdPath, !options.watch);

        if (options.watch) {
          console.log(info("Watching .context/ for changes... (Ctrl+C to stop)"));

          const watcher = watch(contextDir, { recursive: false }, (eventType, filename) => {
            if (filename?.endsWith(".md")) {
              console.log(dim(`  detected change in ${filename}`));
              generateAndWrite(cwd, agentsMdPath, false).catch((err) => {
                console.error(themeError(`Failed to regenerate: ${err instanceof Error ? err.message : String(err)}`));
              });
            }
          });

          // Graceful shutdown on SIGINT
          process.on("SIGINT", () => {
            watcher.close();
            process.exit(0);
          });

          // Keep process alive
          await new Promise(() => {});
        }
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        console.error(themeError(`Failed to generate AGENTS.md: ${message}`));
        process.exitCode = 1;
      }
    });
}
